### ISSUE TITLE
[Meta] User-Flows und Status

### ISSUE THREAD

**Issue by benbender** [impfen/apps-inoeg#49]
Blocked by https://github.com/kiebitz-oss/apps-inoeg/issues/50

# Mediator
- [ ] Login mit MediatorKeyPair
  - [ ] IntegrationTest
- [ ] Bestätigung Provider
  - [ ] IntegrationTest
- ...

# Provider
- [ ] Anmeldung
  - [ ] IntegrationTest
- [ ] Login mit MediatorKeyPair + Secret
  - [ ] IntegrationTest
- [ ] Update eigene Daten
  - [ ] IntegrationTest
- [ ] Einzeltermin einstellen
  - [ ] IntegrationTest
- [ ] Terminserie einstellen
  - [ ] IntegrationTest
- ...

# User
- [ ] Terminbuchung
  - [ ] IntegrationTest
- ...
