### ISSUE TITLE
Meta: Vanellus-Refactoring

### ISSUE THREAD

**Issue by benbender** [impfen/apps-inoeg#52]
- [x] https://github.com/kiebitz-oss/apps-inoeg/issues/45
- [x] https://github.com/kiebitz-oss/apps-inoeg/issues/44
- [x] https://github.com/kiebitz-oss/apps-inoeg/issues/43
- [x] https://github.com/kiebitz-oss/apps-inoeg/issues/42
